/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Size } from "./components/gwds-icon/gwds-icon";
export namespace Components {
    interface GwdsAccordion {
        "bgColor": string;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
    }
    interface GwdsAccordionItem {
        "active": boolean;
        "itemId": string;
        "itemTitle": string;
    }
    interface GwdsAvatar {
        "imgAlt": string;
        "imgUrl": string;
        "line": boolean;
        "size": 'm' | 'l' | 'xl' | 'xxl';
    }
    interface GwdsBlocks {
        "bgColor": string;
        "description": string;
        "display": 'grid-2' | 'grid-3' | 'grid-aside';
        "firstButtonLabel": string;
        "firstButtonTarget": '_blank' | '_self';
        "firstButtonType": 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl": string;
        "linkLabel": string;
        "linkTarget": '_blank' | '_self';
        "linkUrl": string;
        "mainTitle": string;
        "secondButtonLabel": string;
        "secondButtonTarget": '_blank' | '_self';
        "secondButtonType": 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl": string;
        "thirdButtonLabel": string;
        "thirdButtonTarget": '_blank' | '_self';
        "thirdButtonType": 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl": string;
    }
    interface GwdsBreadcrumbs {
        "url": string;
    }
    interface GwdsButton {
        "label": string;
        "m0": boolean;
        "size": 'small' | 'regular';
        "target": '_blank' | '_self';
        "type": 'primary' | 'secondary' | 'tertiary';
        "url": string;
    }
    interface GwdsCard {
        "bgColor": string;
        "description": string;
        "imgAlt": string;
        "imgSrc": string;
        "linkLabel": string;
        "linkTarget": string;
        "linkUrl": string;
        "noShadow": boolean;
        "tagLabel": string;
        "titleLabel": string;
    }
    interface GwdsComponentTitle {
        "experimental": boolean;
        "label": string;
    }
    interface GwdsFormInput {
        "maxWidth": string;
        "minWidth": string;
        "placeholder": string;
    }
    interface GwdsGoodNews {
        "authorAvatarAlt": string;
        "authorAvatarUrl": string;
        "authorName": string;
        "category": string;
        "date": string;
        "imgAlt": string;
        "imgUrl": string;
        "layout": 'l1' | 'l2';
        "newsTitle": string;
        "url": string;
    }
    interface GwdsGoodNewsSection {
        "data": Array<Object> | undefined;
        "layout": 'l1' | 'l2';
        "sectionTitle": string;
        "test": string;
    }
    interface GwdsGradientTitle {
        "center": boolean;
        "from": string;
        "to": string;
    }
    interface GwdsGrid {
        "gap": 'xs' | 's' | 'm';
        "perRow": '2' | '3' | '4' | '6';
    }
    interface GwdsIcon {
        /**
          * The color of the icon.
         */
        "color": string;
        /**
          * If enabled, the icon will be loaded lazily when it's visible in the viewport.
         */
        "lazy": boolean;
        /**
          * The size of the icon. Possible values: small, medium, large.
         */
        "size": Size;
        /**
          * The URL of the icon.
         */
        "src": string;
    }
    interface GwdsLanguageSwitcher {
        "enUrl": string;
        "esUrl": string;
        "ptUrl": string;
        "selectedLang": 'en' | 'es' | 'pt';
    }
    interface GwdsLearnMore {
        "bgColor": string;
        "firstButtonLabel": string;
        "firstButtonTarget": '_blank' | '_self';
        "firstButtonType": 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl": string;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
        "secondButtonLabel": string;
        "secondButtonTarget": '_blank' | '_self';
        "secondButtonType": 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl": string;
        "thirdButtonLabel": string;
        "thirdButtonTarget": '_blank' | '_self';
        "thirdButtonType": 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl": string;
    }
    interface GwdsList {
        "bgColor": string;
        "description": string;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
    }
    interface GwdsListItem {
        "iconAlt": string;
        "iconUrl": string;
    }
    interface GwdsLogo {
        "imgAlt": string;
        "imgSrc": string;
        "label": string;
        "linkUrl": string;
        "name": string;
        "size": string;
    }
    interface GwdsLogos {
        "mainTitle": string;
    }
    interface GwdsLookAtMe {
        "alignContent": 'left' | 'center' | 'right';
        "bgColor": string;
        "bgImage": string;
        "bgSize": string;
        "description": string;
        "firstButtonLabel": string;
        "firstButtonTarget": '_blank' | '_self';
        "firstButtonType": 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl": string;
        "mainTitle": string;
        "pb0": boolean;
        "preTitle": string;
        "pt0": boolean;
        "secondButtonLabel": string;
        "secondButtonTarget": '_blank' | '_self';
        "secondButtonType": 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl": string;
        "thirdButtonLabel": string;
        "thirdButtonTarget": '_blank' | '_self';
        "thirdButtonType": 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl": string;
    }
    interface GwdsMessage {
        "bgColor": string;
        "buttonCloses": boolean;
        "buttonLabel": string;
        "buttonTarget": '_blank' | '_self';
        "buttonUrl": string;
        "closed": boolean;
        "fixed": boolean;
        "hideClose": boolean;
        "linkLabel": string;
        "linkTarget": '_blank' | '_self';
        "linkUrl": string;
    }
    interface GwdsQuote {
        "bgColor": string;
        "centerVertical": boolean;
        "cite": string;
        "imageAlt": string;
        "imageUrl": string;
        "personLocation": string;
        "personName": string;
        "whiteText": boolean;
    }
    interface GwdsShowAndTell {
        "alignContent": 'left' | 'right';
        "bgColor": string;
        "firstButtonLabel": string;
        "firstButtonTarget": '_blank' | '_self';
        "firstButtonType": 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl": string;
        "imageAlt": string;
        "imageUrl": string;
        "mainTitle": string;
        "pb0": boolean;
        "preTitle": string;
        "pt0": boolean;
        "secondButtonLabel": string;
        "secondButtonTarget": '_blank' | '_self';
        "secondButtonType": 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl": string;
        "thirdButtonLabel": string;
        "thirdButtonTarget": '_blank' | '_self';
        "thirdButtonType": 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl": string;
    }
    interface GwdsSlider {
        "cards": boolean;
        "cover": boolean;
        "dark": boolean;
        "gap": boolean;
        "individual": boolean;
        "orientation": 'landscape' | 'portrait';
        "padding": boolean;
        "sliderId": string;
    }
    interface GwdsStack {
        "bgColor": string;
        "description": string;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
    }
    interface GwdsStack2 {
        "bgColor": string;
        "description": string;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
    }
    interface GwdsStackItem {
        "buttonBlank": boolean;
        "buttonLabel": string;
        "buttonUrl": string;
        "iconAlt": string;
        "iconUrl": string;
        "mainTitle": string;
        "visible": boolean;
    }
    interface GwdsTag {
        "bgColor": string;
        "label": string;
        "url": string;
    }
    interface GwdsTooltip {
        "label": string;
        "position": 'top' | 'right' | 'bottom' | 'left';
        "width": string;
    }
    interface GwdsVideo {
        "fullWidth": boolean;
        "source": 'youtube' | 'vimeo';
        "videoId": string;
    }
    interface GwdsVideoLite {
        "maxWidth": string;
        "params": string;
        "playLabel": string;
        "poster": string;
        "videoId": string;
    }
    interface GwdsVideoSection {
        "alignContent": 'left' | 'right';
        "bgColor": string;
        "firstButtonLabel": string;
        "firstButtonTarget": '_blank' | '_self';
        "firstButtonType": 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl": string;
        "lite": boolean;
        "mainTitle": string;
        "pb0": boolean;
        "pt0": boolean;
        "secondButtonLabel": string;
        "secondButtonTarget": '_blank' | '_self';
        "secondButtonType": 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl": string;
        "thirdButtonLabel": string;
        "thirdButtonTarget": '_blank' | '_self';
        "thirdButtonType": 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl": string;
        "videoId": string;
        "videoPoster": string;
    }
    interface Live2022Card {
        "bgColor": string;
        "cardTitle": string;
        "imageAlt": string;
        "imageUrl": string;
        "maxWidth": string;
        "minWidth": string;
        "speaker1AvatarUrl": string;
        "speaker1Name": string;
        "speaker2AvatarUrl": string;
        "speaker2Name": string;
        "url": string;
    }
    interface Live2022SearchBox {
    }
}
export interface GwdsAccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGwdsAccordionItemElement;
}
declare global {
    interface HTMLGwdsAccordionElement extends Components.GwdsAccordion, HTMLStencilElement {
    }
    var HTMLGwdsAccordionElement: {
        prototype: HTMLGwdsAccordionElement;
        new (): HTMLGwdsAccordionElement;
    };
    interface HTMLGwdsAccordionItemElement extends Components.GwdsAccordionItem, HTMLStencilElement {
    }
    var HTMLGwdsAccordionItemElement: {
        prototype: HTMLGwdsAccordionItemElement;
        new (): HTMLGwdsAccordionItemElement;
    };
    interface HTMLGwdsAvatarElement extends Components.GwdsAvatar, HTMLStencilElement {
    }
    var HTMLGwdsAvatarElement: {
        prototype: HTMLGwdsAvatarElement;
        new (): HTMLGwdsAvatarElement;
    };
    interface HTMLGwdsBlocksElement extends Components.GwdsBlocks, HTMLStencilElement {
    }
    var HTMLGwdsBlocksElement: {
        prototype: HTMLGwdsBlocksElement;
        new (): HTMLGwdsBlocksElement;
    };
    interface HTMLGwdsBreadcrumbsElement extends Components.GwdsBreadcrumbs, HTMLStencilElement {
    }
    var HTMLGwdsBreadcrumbsElement: {
        prototype: HTMLGwdsBreadcrumbsElement;
        new (): HTMLGwdsBreadcrumbsElement;
    };
    interface HTMLGwdsButtonElement extends Components.GwdsButton, HTMLStencilElement {
    }
    var HTMLGwdsButtonElement: {
        prototype: HTMLGwdsButtonElement;
        new (): HTMLGwdsButtonElement;
    };
    interface HTMLGwdsCardElement extends Components.GwdsCard, HTMLStencilElement {
    }
    var HTMLGwdsCardElement: {
        prototype: HTMLGwdsCardElement;
        new (): HTMLGwdsCardElement;
    };
    interface HTMLGwdsComponentTitleElement extends Components.GwdsComponentTitle, HTMLStencilElement {
    }
    var HTMLGwdsComponentTitleElement: {
        prototype: HTMLGwdsComponentTitleElement;
        new (): HTMLGwdsComponentTitleElement;
    };
    interface HTMLGwdsFormInputElement extends Components.GwdsFormInput, HTMLStencilElement {
    }
    var HTMLGwdsFormInputElement: {
        prototype: HTMLGwdsFormInputElement;
        new (): HTMLGwdsFormInputElement;
    };
    interface HTMLGwdsGoodNewsElement extends Components.GwdsGoodNews, HTMLStencilElement {
    }
    var HTMLGwdsGoodNewsElement: {
        prototype: HTMLGwdsGoodNewsElement;
        new (): HTMLGwdsGoodNewsElement;
    };
    interface HTMLGwdsGoodNewsSectionElement extends Components.GwdsGoodNewsSection, HTMLStencilElement {
    }
    var HTMLGwdsGoodNewsSectionElement: {
        prototype: HTMLGwdsGoodNewsSectionElement;
        new (): HTMLGwdsGoodNewsSectionElement;
    };
    interface HTMLGwdsGradientTitleElement extends Components.GwdsGradientTitle, HTMLStencilElement {
    }
    var HTMLGwdsGradientTitleElement: {
        prototype: HTMLGwdsGradientTitleElement;
        new (): HTMLGwdsGradientTitleElement;
    };
    interface HTMLGwdsGridElement extends Components.GwdsGrid, HTMLStencilElement {
    }
    var HTMLGwdsGridElement: {
        prototype: HTMLGwdsGridElement;
        new (): HTMLGwdsGridElement;
    };
    interface HTMLGwdsIconElement extends Components.GwdsIcon, HTMLStencilElement {
    }
    var HTMLGwdsIconElement: {
        prototype: HTMLGwdsIconElement;
        new (): HTMLGwdsIconElement;
    };
    interface HTMLGwdsLanguageSwitcherElement extends Components.GwdsLanguageSwitcher, HTMLStencilElement {
    }
    var HTMLGwdsLanguageSwitcherElement: {
        prototype: HTMLGwdsLanguageSwitcherElement;
        new (): HTMLGwdsLanguageSwitcherElement;
    };
    interface HTMLGwdsLearnMoreElement extends Components.GwdsLearnMore, HTMLStencilElement {
    }
    var HTMLGwdsLearnMoreElement: {
        prototype: HTMLGwdsLearnMoreElement;
        new (): HTMLGwdsLearnMoreElement;
    };
    interface HTMLGwdsListElement extends Components.GwdsList, HTMLStencilElement {
    }
    var HTMLGwdsListElement: {
        prototype: HTMLGwdsListElement;
        new (): HTMLGwdsListElement;
    };
    interface HTMLGwdsListItemElement extends Components.GwdsListItem, HTMLStencilElement {
    }
    var HTMLGwdsListItemElement: {
        prototype: HTMLGwdsListItemElement;
        new (): HTMLGwdsListItemElement;
    };
    interface HTMLGwdsLogoElement extends Components.GwdsLogo, HTMLStencilElement {
    }
    var HTMLGwdsLogoElement: {
        prototype: HTMLGwdsLogoElement;
        new (): HTMLGwdsLogoElement;
    };
    interface HTMLGwdsLogosElement extends Components.GwdsLogos, HTMLStencilElement {
    }
    var HTMLGwdsLogosElement: {
        prototype: HTMLGwdsLogosElement;
        new (): HTMLGwdsLogosElement;
    };
    interface HTMLGwdsLookAtMeElement extends Components.GwdsLookAtMe, HTMLStencilElement {
    }
    var HTMLGwdsLookAtMeElement: {
        prototype: HTMLGwdsLookAtMeElement;
        new (): HTMLGwdsLookAtMeElement;
    };
    interface HTMLGwdsMessageElement extends Components.GwdsMessage, HTMLStencilElement {
    }
    var HTMLGwdsMessageElement: {
        prototype: HTMLGwdsMessageElement;
        new (): HTMLGwdsMessageElement;
    };
    interface HTMLGwdsQuoteElement extends Components.GwdsQuote, HTMLStencilElement {
    }
    var HTMLGwdsQuoteElement: {
        prototype: HTMLGwdsQuoteElement;
        new (): HTMLGwdsQuoteElement;
    };
    interface HTMLGwdsShowAndTellElement extends Components.GwdsShowAndTell, HTMLStencilElement {
    }
    var HTMLGwdsShowAndTellElement: {
        prototype: HTMLGwdsShowAndTellElement;
        new (): HTMLGwdsShowAndTellElement;
    };
    interface HTMLGwdsSliderElement extends Components.GwdsSlider, HTMLStencilElement {
    }
    var HTMLGwdsSliderElement: {
        prototype: HTMLGwdsSliderElement;
        new (): HTMLGwdsSliderElement;
    };
    interface HTMLGwdsStackElement extends Components.GwdsStack, HTMLStencilElement {
    }
    var HTMLGwdsStackElement: {
        prototype: HTMLGwdsStackElement;
        new (): HTMLGwdsStackElement;
    };
    interface HTMLGwdsStack2Element extends Components.GwdsStack2, HTMLStencilElement {
    }
    var HTMLGwdsStack2Element: {
        prototype: HTMLGwdsStack2Element;
        new (): HTMLGwdsStack2Element;
    };
    interface HTMLGwdsStackItemElement extends Components.GwdsStackItem, HTMLStencilElement {
    }
    var HTMLGwdsStackItemElement: {
        prototype: HTMLGwdsStackItemElement;
        new (): HTMLGwdsStackItemElement;
    };
    interface HTMLGwdsTagElement extends Components.GwdsTag, HTMLStencilElement {
    }
    var HTMLGwdsTagElement: {
        prototype: HTMLGwdsTagElement;
        new (): HTMLGwdsTagElement;
    };
    interface HTMLGwdsTooltipElement extends Components.GwdsTooltip, HTMLStencilElement {
    }
    var HTMLGwdsTooltipElement: {
        prototype: HTMLGwdsTooltipElement;
        new (): HTMLGwdsTooltipElement;
    };
    interface HTMLGwdsVideoElement extends Components.GwdsVideo, HTMLStencilElement {
    }
    var HTMLGwdsVideoElement: {
        prototype: HTMLGwdsVideoElement;
        new (): HTMLGwdsVideoElement;
    };
    interface HTMLGwdsVideoLiteElement extends Components.GwdsVideoLite, HTMLStencilElement {
    }
    var HTMLGwdsVideoLiteElement: {
        prototype: HTMLGwdsVideoLiteElement;
        new (): HTMLGwdsVideoLiteElement;
    };
    interface HTMLGwdsVideoSectionElement extends Components.GwdsVideoSection, HTMLStencilElement {
    }
    var HTMLGwdsVideoSectionElement: {
        prototype: HTMLGwdsVideoSectionElement;
        new (): HTMLGwdsVideoSectionElement;
    };
    interface HTMLLive2022CardElement extends Components.Live2022Card, HTMLStencilElement {
    }
    var HTMLLive2022CardElement: {
        prototype: HTMLLive2022CardElement;
        new (): HTMLLive2022CardElement;
    };
    interface HTMLLive2022SearchBoxElement extends Components.Live2022SearchBox, HTMLStencilElement {
    }
    var HTMLLive2022SearchBoxElement: {
        prototype: HTMLLive2022SearchBoxElement;
        new (): HTMLLive2022SearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "gwds-accordion": HTMLGwdsAccordionElement;
        "gwds-accordion-item": HTMLGwdsAccordionItemElement;
        "gwds-avatar": HTMLGwdsAvatarElement;
        "gwds-blocks": HTMLGwdsBlocksElement;
        "gwds-breadcrumbs": HTMLGwdsBreadcrumbsElement;
        "gwds-button": HTMLGwdsButtonElement;
        "gwds-card": HTMLGwdsCardElement;
        "gwds-component-title": HTMLGwdsComponentTitleElement;
        "gwds-form-input": HTMLGwdsFormInputElement;
        "gwds-good-news": HTMLGwdsGoodNewsElement;
        "gwds-good-news-section": HTMLGwdsGoodNewsSectionElement;
        "gwds-gradient-title": HTMLGwdsGradientTitleElement;
        "gwds-grid": HTMLGwdsGridElement;
        "gwds-icon": HTMLGwdsIconElement;
        "gwds-language-switcher": HTMLGwdsLanguageSwitcherElement;
        "gwds-learn-more": HTMLGwdsLearnMoreElement;
        "gwds-list": HTMLGwdsListElement;
        "gwds-list-item": HTMLGwdsListItemElement;
        "gwds-logo": HTMLGwdsLogoElement;
        "gwds-logos": HTMLGwdsLogosElement;
        "gwds-look-at-me": HTMLGwdsLookAtMeElement;
        "gwds-message": HTMLGwdsMessageElement;
        "gwds-quote": HTMLGwdsQuoteElement;
        "gwds-show-and-tell": HTMLGwdsShowAndTellElement;
        "gwds-slider": HTMLGwdsSliderElement;
        "gwds-stack": HTMLGwdsStackElement;
        "gwds-stack-2": HTMLGwdsStack2Element;
        "gwds-stack-item": HTMLGwdsStackItemElement;
        "gwds-tag": HTMLGwdsTagElement;
        "gwds-tooltip": HTMLGwdsTooltipElement;
        "gwds-video": HTMLGwdsVideoElement;
        "gwds-video-lite": HTMLGwdsVideoLiteElement;
        "gwds-video-section": HTMLGwdsVideoSectionElement;
        "live-2022-card": HTMLLive2022CardElement;
        "live-2022-search-box": HTMLLive2022SearchBoxElement;
    }
}
declare namespace LocalJSX {
    interface GwdsAccordion {
        "bgColor"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
    }
    interface GwdsAccordionItem {
        "active"?: boolean;
        "itemId"?: string;
        "itemTitle"?: string;
        "onAccordionOpened"?: (event: GwdsAccordionItemCustomEvent<object>) => void;
    }
    interface GwdsAvatar {
        "imgAlt"?: string;
        "imgUrl"?: string;
        "line"?: boolean;
        "size"?: 'm' | 'l' | 'xl' | 'xxl';
    }
    interface GwdsBlocks {
        "bgColor"?: string;
        "description"?: string;
        "display"?: 'grid-2' | 'grid-3' | 'grid-aside';
        "firstButtonLabel"?: string;
        "firstButtonTarget"?: '_blank' | '_self';
        "firstButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl"?: string;
        "linkLabel"?: string;
        "linkTarget"?: '_blank' | '_self';
        "linkUrl"?: string;
        "mainTitle"?: string;
        "secondButtonLabel"?: string;
        "secondButtonTarget"?: '_blank' | '_self';
        "secondButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl"?: string;
        "thirdButtonLabel"?: string;
        "thirdButtonTarget"?: '_blank' | '_self';
        "thirdButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl"?: string;
    }
    interface GwdsBreadcrumbs {
        "url"?: string;
    }
    interface GwdsButton {
        "label"?: string;
        "m0"?: boolean;
        "size"?: 'small' | 'regular';
        "target"?: '_blank' | '_self';
        "type"?: 'primary' | 'secondary' | 'tertiary';
        "url"?: string;
    }
    interface GwdsCard {
        "bgColor"?: string;
        "description"?: string;
        "imgAlt"?: string;
        "imgSrc"?: string;
        "linkLabel"?: string;
        "linkTarget"?: string;
        "linkUrl"?: string;
        "noShadow"?: boolean;
        "tagLabel"?: string;
        "titleLabel"?: string;
    }
    interface GwdsComponentTitle {
        "experimental"?: boolean;
        "label"?: string;
    }
    interface GwdsFormInput {
        "maxWidth"?: string;
        "minWidth"?: string;
        "placeholder"?: string;
    }
    interface GwdsGoodNews {
        "authorAvatarAlt"?: string;
        "authorAvatarUrl"?: string;
        "authorName"?: string;
        "category"?: string;
        "date"?: string;
        "imgAlt"?: string;
        "imgUrl"?: string;
        "layout"?: 'l1' | 'l2';
        "newsTitle"?: string;
        "url"?: string;
    }
    interface GwdsGoodNewsSection {
        "data"?: Array<Object> | undefined;
        "layout"?: 'l1' | 'l2';
        "sectionTitle"?: string;
        "test"?: string;
    }
    interface GwdsGradientTitle {
        "center"?: boolean;
        "from"?: string;
        "to"?: string;
    }
    interface GwdsGrid {
        "gap"?: 'xs' | 's' | 'm';
        "perRow"?: '2' | '3' | '4' | '6';
    }
    interface GwdsIcon {
        /**
          * The color of the icon.
         */
        "color"?: string;
        /**
          * If enabled, the icon will be loaded lazily when it's visible in the viewport.
         */
        "lazy"?: boolean;
        /**
          * The size of the icon. Possible values: small, medium, large.
         */
        "size"?: Size;
        /**
          * The URL of the icon.
         */
        "src"?: string;
    }
    interface GwdsLanguageSwitcher {
        "enUrl"?: string;
        "esUrl"?: string;
        "ptUrl"?: string;
        "selectedLang"?: 'en' | 'es' | 'pt';
    }
    interface GwdsLearnMore {
        "bgColor"?: string;
        "firstButtonLabel"?: string;
        "firstButtonTarget"?: '_blank' | '_self';
        "firstButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
        "secondButtonLabel"?: string;
        "secondButtonTarget"?: '_blank' | '_self';
        "secondButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl"?: string;
        "thirdButtonLabel"?: string;
        "thirdButtonTarget"?: '_blank' | '_self';
        "thirdButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl"?: string;
    }
    interface GwdsList {
        "bgColor"?: string;
        "description"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
    }
    interface GwdsListItem {
        "iconAlt"?: string;
        "iconUrl"?: string;
    }
    interface GwdsLogo {
        "imgAlt"?: string;
        "imgSrc"?: string;
        "label"?: string;
        "linkUrl"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface GwdsLogos {
        "mainTitle"?: string;
    }
    interface GwdsLookAtMe {
        "alignContent"?: 'left' | 'center' | 'right';
        "bgColor"?: string;
        "bgImage"?: string;
        "bgSize"?: string;
        "description"?: string;
        "firstButtonLabel"?: string;
        "firstButtonTarget"?: '_blank' | '_self';
        "firstButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "preTitle"?: string;
        "pt0"?: boolean;
        "secondButtonLabel"?: string;
        "secondButtonTarget"?: '_blank' | '_self';
        "secondButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl"?: string;
        "thirdButtonLabel"?: string;
        "thirdButtonTarget"?: '_blank' | '_self';
        "thirdButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl"?: string;
    }
    interface GwdsMessage {
        "bgColor"?: string;
        "buttonCloses"?: boolean;
        "buttonLabel"?: string;
        "buttonTarget"?: '_blank' | '_self';
        "buttonUrl"?: string;
        "closed"?: boolean;
        "fixed"?: boolean;
        "hideClose"?: boolean;
        "linkLabel"?: string;
        "linkTarget"?: '_blank' | '_self';
        "linkUrl"?: string;
    }
    interface GwdsQuote {
        "bgColor"?: string;
        "centerVertical"?: boolean;
        "cite"?: string;
        "imageAlt"?: string;
        "imageUrl"?: string;
        "personLocation"?: string;
        "personName"?: string;
        "whiteText"?: boolean;
    }
    interface GwdsShowAndTell {
        "alignContent"?: 'left' | 'right';
        "bgColor"?: string;
        "firstButtonLabel"?: string;
        "firstButtonTarget"?: '_blank' | '_self';
        "firstButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl"?: string;
        "imageAlt"?: string;
        "imageUrl"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "preTitle"?: string;
        "pt0"?: boolean;
        "secondButtonLabel"?: string;
        "secondButtonTarget"?: '_blank' | '_self';
        "secondButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl"?: string;
        "thirdButtonLabel"?: string;
        "thirdButtonTarget"?: '_blank' | '_self';
        "thirdButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl"?: string;
    }
    interface GwdsSlider {
        "cards"?: boolean;
        "cover"?: boolean;
        "dark"?: boolean;
        "gap"?: boolean;
        "individual"?: boolean;
        "orientation"?: 'landscape' | 'portrait';
        "padding"?: boolean;
        "sliderId"?: string;
    }
    interface GwdsStack {
        "bgColor"?: string;
        "description"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
    }
    interface GwdsStack2 {
        "bgColor"?: string;
        "description"?: string;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
    }
    interface GwdsStackItem {
        "buttonBlank"?: boolean;
        "buttonLabel"?: string;
        "buttonUrl"?: string;
        "iconAlt"?: string;
        "iconUrl"?: string;
        "mainTitle"?: string;
        "visible"?: boolean;
    }
    interface GwdsTag {
        "bgColor"?: string;
        "label"?: string;
        "url"?: string;
    }
    interface GwdsTooltip {
        "label"?: string;
        "position"?: 'top' | 'right' | 'bottom' | 'left';
        "width"?: string;
    }
    interface GwdsVideo {
        "fullWidth"?: boolean;
        "source"?: 'youtube' | 'vimeo';
        "videoId"?: string;
    }
    interface GwdsVideoLite {
        "maxWidth"?: string;
        "params"?: string;
        "playLabel"?: string;
        "poster"?: string;
        "videoId"?: string;
    }
    interface GwdsVideoSection {
        "alignContent"?: 'left' | 'right';
        "bgColor"?: string;
        "firstButtonLabel"?: string;
        "firstButtonTarget"?: '_blank' | '_self';
        "firstButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "firstButtonUrl"?: string;
        "lite"?: boolean;
        "mainTitle"?: string;
        "pb0"?: boolean;
        "pt0"?: boolean;
        "secondButtonLabel"?: string;
        "secondButtonTarget"?: '_blank' | '_self';
        "secondButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "secondButtonUrl"?: string;
        "thirdButtonLabel"?: string;
        "thirdButtonTarget"?: '_blank' | '_self';
        "thirdButtonType"?: 'primary' | 'secondary' | 'tertiary';
        "thirdButtonUrl"?: string;
        "videoId"?: string;
        "videoPoster"?: string;
    }
    interface Live2022Card {
        "bgColor"?: string;
        "cardTitle"?: string;
        "imageAlt"?: string;
        "imageUrl"?: string;
        "maxWidth"?: string;
        "minWidth"?: string;
        "speaker1AvatarUrl"?: string;
        "speaker1Name"?: string;
        "speaker2AvatarUrl"?: string;
        "speaker2Name"?: string;
        "url"?: string;
    }
    interface Live2022SearchBox {
    }
    interface IntrinsicElements {
        "gwds-accordion": GwdsAccordion;
        "gwds-accordion-item": GwdsAccordionItem;
        "gwds-avatar": GwdsAvatar;
        "gwds-blocks": GwdsBlocks;
        "gwds-breadcrumbs": GwdsBreadcrumbs;
        "gwds-button": GwdsButton;
        "gwds-card": GwdsCard;
        "gwds-component-title": GwdsComponentTitle;
        "gwds-form-input": GwdsFormInput;
        "gwds-good-news": GwdsGoodNews;
        "gwds-good-news-section": GwdsGoodNewsSection;
        "gwds-gradient-title": GwdsGradientTitle;
        "gwds-grid": GwdsGrid;
        "gwds-icon": GwdsIcon;
        "gwds-language-switcher": GwdsLanguageSwitcher;
        "gwds-learn-more": GwdsLearnMore;
        "gwds-list": GwdsList;
        "gwds-list-item": GwdsListItem;
        "gwds-logo": GwdsLogo;
        "gwds-logos": GwdsLogos;
        "gwds-look-at-me": GwdsLookAtMe;
        "gwds-message": GwdsMessage;
        "gwds-quote": GwdsQuote;
        "gwds-show-and-tell": GwdsShowAndTell;
        "gwds-slider": GwdsSlider;
        "gwds-stack": GwdsStack;
        "gwds-stack-2": GwdsStack2;
        "gwds-stack-item": GwdsStackItem;
        "gwds-tag": GwdsTag;
        "gwds-tooltip": GwdsTooltip;
        "gwds-video": GwdsVideo;
        "gwds-video-lite": GwdsVideoLite;
        "gwds-video-section": GwdsVideoSection;
        "live-2022-card": Live2022Card;
        "live-2022-search-box": Live2022SearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gwds-accordion": LocalJSX.GwdsAccordion & JSXBase.HTMLAttributes<HTMLGwdsAccordionElement>;
            "gwds-accordion-item": LocalJSX.GwdsAccordionItem & JSXBase.HTMLAttributes<HTMLGwdsAccordionItemElement>;
            "gwds-avatar": LocalJSX.GwdsAvatar & JSXBase.HTMLAttributes<HTMLGwdsAvatarElement>;
            "gwds-blocks": LocalJSX.GwdsBlocks & JSXBase.HTMLAttributes<HTMLGwdsBlocksElement>;
            "gwds-breadcrumbs": LocalJSX.GwdsBreadcrumbs & JSXBase.HTMLAttributes<HTMLGwdsBreadcrumbsElement>;
            "gwds-button": LocalJSX.GwdsButton & JSXBase.HTMLAttributes<HTMLGwdsButtonElement>;
            "gwds-card": LocalJSX.GwdsCard & JSXBase.HTMLAttributes<HTMLGwdsCardElement>;
            "gwds-component-title": LocalJSX.GwdsComponentTitle & JSXBase.HTMLAttributes<HTMLGwdsComponentTitleElement>;
            "gwds-form-input": LocalJSX.GwdsFormInput & JSXBase.HTMLAttributes<HTMLGwdsFormInputElement>;
            "gwds-good-news": LocalJSX.GwdsGoodNews & JSXBase.HTMLAttributes<HTMLGwdsGoodNewsElement>;
            "gwds-good-news-section": LocalJSX.GwdsGoodNewsSection & JSXBase.HTMLAttributes<HTMLGwdsGoodNewsSectionElement>;
            "gwds-gradient-title": LocalJSX.GwdsGradientTitle & JSXBase.HTMLAttributes<HTMLGwdsGradientTitleElement>;
            "gwds-grid": LocalJSX.GwdsGrid & JSXBase.HTMLAttributes<HTMLGwdsGridElement>;
            "gwds-icon": LocalJSX.GwdsIcon & JSXBase.HTMLAttributes<HTMLGwdsIconElement>;
            "gwds-language-switcher": LocalJSX.GwdsLanguageSwitcher & JSXBase.HTMLAttributes<HTMLGwdsLanguageSwitcherElement>;
            "gwds-learn-more": LocalJSX.GwdsLearnMore & JSXBase.HTMLAttributes<HTMLGwdsLearnMoreElement>;
            "gwds-list": LocalJSX.GwdsList & JSXBase.HTMLAttributes<HTMLGwdsListElement>;
            "gwds-list-item": LocalJSX.GwdsListItem & JSXBase.HTMLAttributes<HTMLGwdsListItemElement>;
            "gwds-logo": LocalJSX.GwdsLogo & JSXBase.HTMLAttributes<HTMLGwdsLogoElement>;
            "gwds-logos": LocalJSX.GwdsLogos & JSXBase.HTMLAttributes<HTMLGwdsLogosElement>;
            "gwds-look-at-me": LocalJSX.GwdsLookAtMe & JSXBase.HTMLAttributes<HTMLGwdsLookAtMeElement>;
            "gwds-message": LocalJSX.GwdsMessage & JSXBase.HTMLAttributes<HTMLGwdsMessageElement>;
            "gwds-quote": LocalJSX.GwdsQuote & JSXBase.HTMLAttributes<HTMLGwdsQuoteElement>;
            "gwds-show-and-tell": LocalJSX.GwdsShowAndTell & JSXBase.HTMLAttributes<HTMLGwdsShowAndTellElement>;
            "gwds-slider": LocalJSX.GwdsSlider & JSXBase.HTMLAttributes<HTMLGwdsSliderElement>;
            "gwds-stack": LocalJSX.GwdsStack & JSXBase.HTMLAttributes<HTMLGwdsStackElement>;
            "gwds-stack-2": LocalJSX.GwdsStack2 & JSXBase.HTMLAttributes<HTMLGwdsStack2Element>;
            "gwds-stack-item": LocalJSX.GwdsStackItem & JSXBase.HTMLAttributes<HTMLGwdsStackItemElement>;
            "gwds-tag": LocalJSX.GwdsTag & JSXBase.HTMLAttributes<HTMLGwdsTagElement>;
            "gwds-tooltip": LocalJSX.GwdsTooltip & JSXBase.HTMLAttributes<HTMLGwdsTooltipElement>;
            "gwds-video": LocalJSX.GwdsVideo & JSXBase.HTMLAttributes<HTMLGwdsVideoElement>;
            "gwds-video-lite": LocalJSX.GwdsVideoLite & JSXBase.HTMLAttributes<HTMLGwdsVideoLiteElement>;
            "gwds-video-section": LocalJSX.GwdsVideoSection & JSXBase.HTMLAttributes<HTMLGwdsVideoSectionElement>;
            "live-2022-card": LocalJSX.Live2022Card & JSXBase.HTMLAttributes<HTMLLive2022CardElement>;
            "live-2022-search-box": LocalJSX.Live2022SearchBox & JSXBase.HTMLAttributes<HTMLLive2022SearchBoxElement>;
        }
    }
}
